<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGPgxgTx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGPgxgTx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGPgxgTx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGPgxgTx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGPgxgTx\App_KernelDevDebugContainer([
    'container.build_hash' => 'GPgxgTx',
    'container.build_id' => '4bb9a9f0',
    'container.build_time' => 1646756306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGPgxgTx');
